export const ERROR_CODES = {
  NOT_FOUND: 'NOT_FOUND',
  BAD_USER_INPUT: 'BAD_USER_INPUT',
} as const;

export const VALIDATION_LIMITS = {
  TEXT_MAX_LENGTH: 500,
  TITLE_MAX_LENGTH: 200,
  DESC_MAX_LENGTH: 2000,
  OPTION_MAX_LENGTH: 200,
  MAX_QUESTIONS: 100,
  MAX_ANSWERS: 1000,
  MAX_ANSWER_VALUES: 100,
} as const;
